"""add deep love reading

Revision ID: 027d3d68cf1d
Revises: 2ff157e40f1a
Create Date: 2026-07-12 17:18:21.373125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027d3d68cf1d'
down_revision = '2ff157e40f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_love_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('card1_slug', sa.String(length=100), nullable=False),
    sa.Column('card1_orientation', sa.String(length=20), nullable=False),
    sa.Column('card2_slug', sa.String(length=100), nullable=False),
    sa.Column('card2_orientation', sa.String(length=20), nullable=False),
    sa.Column('card3_slug', sa.String(length=100), nullable=False),
    sa.Column('card3_orientation', sa.String(length=20), nullable=False),
    sa.Column('card4_slug', sa.String(length=100), nullable=False),
    sa.Column('card4_orientation', sa.String(length=20), nullable=False),
    sa.Column('card5_slug', sa.String(length=100), nullable=False),
    sa.Column('card5_orientation', sa.String(length=20), nullable=False),
    sa.Column('ai_reading', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deep_love_readings')
    # ### end Alembic commands ###
