"""Add premium fields to users

Revision ID: 7c66bd00945f
Revises: ec5f9ae49034
Create Date: 2026-08-19 04:39:35.110089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c66bd00945f'
down_revision = 'ec5f9ae49034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_premium',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0")
            )
        )
        batch_op.add_column(sa.Column('premium_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('premium_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('premium_expires_at')
        batch_op.drop_column('premium_plan')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
