"""Remove premium fields from users

Revision ID: fa3f3fffbe50
Revises: 7c66bd00945f
Create Date: 2026-08-19 15:02:46.236941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3f3fffbe50'
down_revision = '7c66bd00945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('premium_expires_at')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('premium_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_plan', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('premium_expires_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
